language: python
python:
  - "3.8"

services:
  - docker

before_script:
  - pip3 install docker-compose
  - echo STAGE=prod >> codingskills/codingskills/.env

install:
  - pip3 install -r requirements.txt

script:
  - docker-compose up --build -d
  - docker exec -it web-app bash -c "python3 manage.py test"
