version: '3'

services: 
  web-app:
    build: .
    container_name: app
    command: >
      sh-c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      exercises-db:
        condition: service_healthy

  exercises-db:
    image: postgres:12.5
    env_file:
      - codingskills/codingskills/.env
    container_name: exercises-db
    environment:
      - POSTGRES_DB=$${DATABASE_NAME}
      - POSTGRES_USER=$${DATABASE_USER}
      - POSTGRES_PASSWORD=$${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 6
    restart: always
