version: '3'

services: 
  web-app:
    build: .
    container_name: web-app
    entrypoint: [ "/bin/sh","-c" ]
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=exercises-db
    command:
      - | 
        python3 manage.py makemigrations
        python3 manage.py migrate && python3 manage.py migrate --run-syncdb
        python3 manage.py runserver
    ports:
      - "8000:8000"
    depends_on:
      exercises-db:
        condition: service_healthy

  exercises-db:
    image: postgres:12.5
    container_name: exercises-db
    environment:
      - POSTGRES_DB=codingskills_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=exercises-db
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 6
    restart: always
