# Generated by Django 3.2.6 on 2021-08-26 11:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_content', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_input', models.TextField()),
                ('test_result', models.TextField()),
                ('language', models.TextField()),
                ('exercise_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.exercise')),
            ],
        ),
    ]
