# Generated by Django 3.2.6 on 2021-08-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise_id',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='exercise_id',
            new_name='exercise',
        ),
    ]
